apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: tinyurl
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/tinyurl_auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: tinyurl
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: localhost:5000/distributed-tinyurl-auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: auth-service-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: tinyurl
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
