apiVersion: v1
kind: ConfigMap
metadata:
  name: url-service-config
  namespace: tinyurl
data:
  APP_BASE_URL: http://localhost:30081
  JWT_PUBLIC_KEY: replace-with-base64-rsa-public-key
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-urls:5432/tinyurl_urls
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  APP_SNOWFLAKE_NODE_ID_OFFSET: "1"
  APP_SNOWFLAKE_DERIVE_NODE_ID_FROM_HOSTNAME: "true"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: url-service
  namespace: tinyurl
  labels:
    app: url-service
spec:
  serviceName: url-service
  replicas: 2
  selector:
    matchLabels:
      app: url-service
  template:
    metadata:
      labels:
        app: url-service
    spec:
      containers:
        - name: url-service
          image: localhost:5000/distributed-tinyurl-url-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: url-service-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-urls-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-urls-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: url-service
  namespace: tinyurl
spec:
  selector:
    app: url-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
