spring:
  application:
    name: url-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tinyurl_urls
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info