spring:
    application:
        name: analytics-service
    datasource:
        url: jdbc:postgresql://localhost:5434/tinyurl_analytics
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
    flyway:
        enabled: true
    rabbitmq:
        host: ${RABBITMQ_HOST:localhost}
        port: ${RABBITMQ_PORT:5672}
        username: ${RABBITMQ_USERNAME:guest}
        password: ${RABBITMQ_PASSWORD:guest}

server:
    port: 8083

management:
    endpoints:
        web:
            exposure:
                include: health,info

app:
    events:
        clicks:
            exchange: ${CLICK_EVENTS_EXCHANGE:tinyurl.clicks}
            queue: ${CLICK_EVENTS_QUEUE:analytics.click-events}
            routing-key: ${CLICK_EVENTS_ROUTING_KEY:click.recorded}
